[package]
name = "tetrominoes"
version = "0.1.0"
authors = ["Adam Vandolder <adam.vandolder@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
ggez-goodies = "0.5.0"
itertools = "0.8.0"
rand = "0.7.0"

[profile.dev]
opt-level = 1